spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/inuni
    username: inuni_user
    password: dreamteam

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080