services:
  postgres:
    image: postgres:16
    container_name: inuni-postgres

    restart: always

    environment:
      POSTGRES_DB: inuni
      POSTGRES_USER: inuni_user
      POSTGRES_PASSWORD: dreamteam

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: