/** Официальные события (хакатоны от организаторов) */
export const OFFICIAL_EVENTS = [
  {
    id: 'event-1',
    icon: '🤖',
    hot: true,
    name: 'AI Cup Central Asia',
    desc: 'Разрабатывай AI-решения для реального бизнеса. Менторы из Яндекса и Kaspi.',
    date: '20–22 июня 2025',
    prize: '2 000 000 ₸',
    location: 'Онлайн',
    teamSize: '2–4 чел.',
    format: 'online',
    formatLabel: 'Онлайн',
    tags: ['AI', 'ML', 'Python'],
    teamsReg: 87,
    teamsMax: 120,
  },
  {
    id: 'event-2',
    icon: '🏥',
    hot: false,
    name: 'HealthTech Hack 2025',
    desc: 'Создай цифровое решение в сфере здравоохранения. Партнёры — ведущие клиники.',
    date: '5–6 июля 2025',
    prize: '800 000 ₸',
    location: 'Бишкек',
    teamSize: '3–5 чел.',
    format: 'offline',
    formatLabel: 'Оффлайн',
    tags: ['HealthTech', 'UX', 'Backend'],
    teamsReg: 34,
    teamsMax: 60,
  },
  {
    id: 'event-3',
    icon: '💳',
    hot: false,
    name: 'FinHack by Halyk',
    desc: 'Хакатон от Halyk Bank — придумай будущее финансовых продуктов для молодёжи.',
    date: '12–13 июля 2025',
    prize: '3 500 000 ₸',
    location: 'Алматы',
    teamSize: '2–5 чел.',
    format: 'offline',
    formatLabel: 'Оффлайн',
    tags: ['Fintech', 'Mobile', 'UX'],
    teamsReg: 52,
    teamsMax: 80,
  },
  {
    id: 'event-4',
    icon: '🌱',
    hot: false,
    name: 'GreenTech Challenge',
    desc: 'Технологии для экологии и устойчивого развития. Международный формат.',
    date: '19–20 июля 2025',
    prize: '$5 000',
    location: 'Онлайн',
    teamSize: '1–4 чел.',
    format: 'online',
    formatLabel: 'Онлайн',
    tags: ['Sustainability', 'IoT', 'Data'],
    teamsReg: 29,
    teamsMax: 100,
  },
  {
    id: 'event-5',
    icon: '🎓',
    hot: true,
    name: 'EduTech Sprint',
    desc: 'Переизобрети образование. 24 часа на прототип, который меняет то, как люди учатся.',
    date: '26–27 июля 2025',
    prize: '1 200 000 ₸',
    location: 'Нур-Султан',
    teamSize: '3–4 чел.',
    format: 'offline',
    formatLabel: 'Оффлайн',
    tags: ['EdTech', 'AI', 'Design'],
    teamsReg: 41,
    teamsMax: 64,
  },
  {
    id: 'event-6',
    icon: '🔐',
    hot: false,
    name: 'CyberSec Hackathon',
    desc: 'Соревнование по кибербезопасности в формате CTF + продуктовый трек.',
    date: '2–3 авг. 2025',
    prize: '1 000 000 ₸',
    location: 'Онлайн',
    teamSize: '2–3 чел.',
    format: 'online',
    formatLabel: 'Онлайн',
    tags: ['Security', 'CTF', 'Backend'],
    teamsReg: 18,
    teamsMax: 50,
  },
]

export const FEATURED_EVENT = {
  id: 'event-featured',
  name: 'Digital Almaty Hackathon 2025',
  date: '14–16 июня 2025',
  prize: '5 000 000 ₸',
  location: 'Алматы, онлайн',
  teamSize: 'до 5 человек',
}

/** Слоты от студентов (ищут людей в команду) */
export const COMMUNITY_SLOTS = [
  {
    id: 'slot-1',
    icon: '🤖',
    hot: true,
    category: 'hackathon',
    categoryLabel: 'Под хакатон',
    name: 'AI Cup Team — ищем фронт и дизайнера',
    desc: 'Собираем команду на AI Cup Central Asia. Уже есть 2 бэкендщика и ML-инженер. Нужен сильный фронт и дизайнер с портфолио.',
    roles: ['Frontend Dev', 'UI/UX Designer'],
    filledRoles: [],
    team: [
      { initials: 'ИА', color: 'linear-gradient(135deg,#e63946,#1d4ed8)' },
      { initials: 'ДС', color: 'linear-gradient(135deg,#1d4ed8,#06b6d4)' },
    ],
    tags: ['AI', 'Python', 'Vue', 'Hackathon'],
    deadline: 'до 10 июня',
    stage: 'MVP',
    leader: { initials: 'ИА', name: 'Искендер А.', color: 'linear-gradient(135deg,#e63946,#1d4ed8)' },
  },
  {
    id: 'slot-2',
    icon: '💳',
    hot: false,
    category: 'startup',
    categoryLabel: 'Стартап',
    name: 'Fintech-стартап: p2p-кредитование для студентов',
    desc: 'Строим платформу P2P-кредитования для студентов ЦА. Уже есть инвестиционный интерес. Ищем CTO и продакта.',
    roles: ['Backend Dev', 'Product Manager'],
    filledRoles: ['Product Manager'],
    team: [{ initials: 'ЗК', color: 'linear-gradient(135deg,#f97316,#e63946)' }],
    tags: ['Fintech', 'Node.js', 'PostgreSQL'],
    deadline: 'долгосрочно',
    stage: 'Pre-seed',
    leader: { initials: 'ЗК', name: 'Зарина К.', color: 'linear-gradient(135deg,#f97316,#e63946)' },
  },
  {
    id: 'slot-3',
    icon: '🎓',
    hot: false,
    category: 'pet',
    categoryLabel: 'Pet-проект',
    name: 'OpenStudy — AI-планировщик учёбы',
    desc: 'Open-source проект: AI-ассистент, который помогает студентам планировать учёбу, трекать прогресс и учиться эффективнее.',
    roles: ['Frontend Dev', 'ML Engineer', 'Mobile Dev'],
    filledRoles: ['Frontend Dev'],
    team: [
      { initials: 'МБ', color: 'linear-gradient(135deg,#059669,#1d4ed8)' },
      { initials: 'АМ', color: 'linear-gradient(135deg,#7c3aed,#e63946)' },
    ],
    tags: ['EdTech', 'AI', 'Open Source', 'React Native'],
    deadline: 'открыт',
    stage: 'Alpha',
    leader: { initials: 'МБ', name: 'Максат Б.', color: 'linear-gradient(135deg,#059669,#1d4ed8)' },
  },
  {
    id: 'slot-4',
    icon: '🌱',
    hot: false,
    category: 'hackathon',
    categoryLabel: 'Под хакатон',
    name: 'GreenTech Challenge — нужен бэкенд',
    desc: 'Участвуем в GreenTech Challenge. Придумали IoT-решение для мониторинга качества воздуха. Нужен бэкендщик.',
    roles: ['Backend Dev'],
    filledRoles: [],
    team: [
      { initials: 'РМ', color: 'linear-gradient(135deg,#059669,#06b6d4)' },
      { initials: 'СА', color: 'linear-gradient(135deg,#1d4ed8,#7c3aed)' },
    ],
    tags: ['IoT', 'Python', 'Sustainability'],
    deadline: 'до 15 июня',
    stage: 'Concept',
    leader: { initials: 'РМ', name: 'Ренат М.', color: 'linear-gradient(135deg,#059669,#06b6d4)' },
  },
  {
    id: 'slot-5',
    icon: '🎮',
    hot: true,
    category: 'pet',
    categoryLabel: 'Pet-проект',
    name: 'Indie-игра: коллективный рогалик на Unity',
    desc: 'Делаем небольшую инди-игру в жанре rogue-like с мультиплеером. Нужен Unity-разработчик и пиксель-арт дизайнер.',
    roles: ['Unity Dev', 'Pixel Artist'],
    filledRoles: [],
    team: [{ initials: 'ЕП', color: 'linear-gradient(135deg,#f97316,#7c3aed)' }],
    tags: ['GameDev', 'Unity', 'C#', 'Multiplayer'],
    deadline: 'долгосрочно',
    stage: 'Прототип',
    leader: { initials: 'ЕП', name: 'Егор П.', color: 'linear-gradient(135deg,#f97316,#7c3aed)' },
  },
  {
    id: 'slot-6',
    icon: '🏥',
    hot: false,
    category: 'startup',
    categoryLabel: 'Стартап',
    name: 'HealthTrack — трекер здоровья для ЦА',
    desc: 'Строим мобильное приложение для мониторинга хронических заболеваний. Ищем iOS/Android разработчика и ML-инженера.',
    roles: ['Mobile Dev', 'ML Engineer'],
    filledRoles: ['Mobile Dev'],
    team: [
      { initials: 'НО', color: 'linear-gradient(135deg,#e63946,#f97316)' },
      { initials: 'ЖА', color: 'linear-gradient(135deg,#1d4ed8,#06b6d4)' },
    ],
    tags: ['HealthTech', 'Flutter', 'AI', 'Mobile'],
    deadline: 'долгосрочно',
    stage: 'MVP',
    leader: { initials: 'НО', name: 'Назгуль О.', color: 'linear-gradient(135deg,#e63946,#f97316)' },
  },
]

export const CATEGORY_TABS = [
  { key: 'all', label: 'Все' },
  { key: 'hackathon', label: 'Хакатоны' },
  { key: 'startup', label: 'Стартапы' },
  { key: 'pet', label: 'Pet-проекты' },
  { key: 'my', label: 'Мои заявки' },
]

export const THEME_TAGS = ['AI/ML', 'Fintech', 'EdTech', 'HealthTech', 'E-commerce', 'SaaS', 'Social', 'GameDev', 'IoT']
export const ROLE_OPTIONS = ['Frontend', 'Backend', 'ML Engineer', 'UI/UX', 'PM', 'DevOps', 'Mobile', 'Data Analyst']
